// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7JDjzH7g_UCYsLVhxgx6Xc7mhPLx64kY',
    appId: '1:669362370476:web:ab841b7a2701a88ea36c09',
    messagingSenderId: '669362370476',
    projectId: 'omunotexam',
    authDomain: 'omunotexam.firebaseapp.com',
    databaseURL: 'https://omunotexam-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'omunotexam.appspot.com',
    measurementId: 'G-YTN0M2217T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAve95sb5HTXIZ8mzXnomTJigF7r-NVjEQ',
    appId: '1:669362370476:android:7e82bbf56218f58ca36c09',
    messagingSenderId: '669362370476',
    projectId: 'omunotexam',
    databaseURL: 'https://omunotexam-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'omunotexam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoTAJjUJnm0elE8k_eOKc-qnqnNyhZ8TE',
    appId: '1:669362370476:ios:4f70daa0ac9065a9a36c09',
    messagingSenderId: '669362370476',
    projectId: 'omunotexam',
    databaseURL: 'https://omunotexam-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'omunotexam.appspot.com',
    iosClientId: '669362370476-6ed8h3tf48j5blq06ldl5p8cfq75dpt3.apps.googleusercontent.com',
    iosBundleId: 'com.omunot.epikriz',
  );
}
